### ISSUE TITLE
Ошибка при выгрузке исходников из хранилища ERP в Git

### ISSUE THREAD

**Issue by pavlicholeg** [oscript-library/gitsync#168]
Ошибка при выгрузке исходников из хранилища ERP в Git. Что это может быть:

2019-01-30T21:06:53.1073299Z ИНФОРМАЦИЯ - Раскладываем модули по папкам согласно иерархии метаданных
2019-01-30T21:17:43.9273435Z КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\asserts\src\bdd-asserts.os / Ошибка в строке: 336 / [Failed] Ожидали, что проверяемое значение (0) РАВНО (1).
2019-01-30T21:17:43.9273838Z Стек трейс:
2019-01-30T21:17:43.9273953Z   C:\Program Files (x86)\OneScript\lib\asserts\src\bdd-asserts.os / Метод Равно / Строка 71
2019-01-30T21:17:43.9274082Z     C:\Program Files (x86)\OneScript\lib\gitrunner\src\ГитРепозиторий.os / Метод УстановитьКоммитера / Строка 1011
2019-01-30T21:17:43.9274225Z       C:\Program Files (x86)\OneScript\lib\gitrunner\src\ГитРепозиторий.os / Метод Закоммитить / Строка 109
2019-01-30T21:17:43.9274365Z         C:\Program Files (x86)\OneScript\lib\gitsync\src\core\Классы\МенеджерСинхронизации.os / Метод ВыполнитьКоммитГит / Строка 546
2019-01-30T21:17:43.9274531Z           C:\Program Files (x86)\OneScript\lib\gitsync\src\core\Классы\МенеджерСинхронизации.os / Метод СинхронизироватьХранилищеКонфигурацийСГит / Строка 1065
2019-01-30T21:17:43.9274789Z             C:\Program Files (x86)\OneScript\lib\gitsync\src\core\Модули\РаспаковщикКонфигурации.os / Метод ВыполнитьЭкспортИсходников / Строка 89
2019-01-30T21:17:43.9274962Z               C:\Program Files (x86)\OneScript\lib\gitsync\src\core\Классы\КомандаExport.os / Метод ВыполнитьКоманду / Строка 138
2019-01-30T21:17:43.9275129Z                 C:\Program Files (x86)\OneScript\lib\gitsync\src\core\Модули\МенеджерКомандПриложения.os / Метод ВыполнитьКоманду / Строка 64
2019-01-30T21:17:43.9275240Z                   C:\Program Files (x86)\OneScript\lib\gitsync\src\gitsync.os / Метод ВыполнениеКоманды / Строка 63
2019-01-30T21:17:43.9275364Z                     C:\Program Files (x86)\OneScript\lib\gitsync\src\gitsync.os / Метод $entry / Строка 98}
2019-01-30T21:17:44.0165893Z Error: C:\Program Files (x86)\OneScript\bin\gitsync.bat failed with return code: 1
2019-01-30T21:17:44.0166908Z     at ChildProcess.<anonymous> (E:\soft\vsts-agent-win-x64-2.144.0\_work\_tasks\gitsync-1c_fd678ca2-3c88-4309-ba4f-46a4a8372554\0.2.18\node_modules\vsts-task-lib\toolrunner.js:568:30)
2019-01-30T21:17:44.0168002Z     at emitTwo (events.js:106:13)
2019-01-30T21:17:44.0168394Z     at ChildProcess.emit (events.js:191:7)
2019-01-30T21:17:44.0168666Z     at maybeClose (internal/child_process.js:886:16)
2019-01-30T21:17:44.0169141Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
2019-01-30T21:17:44.0252804Z ##[error]C:\Program Files (x86)\OneScript\bin\gitsync.bat failed with return code: 1

**Comment by pavlicholeg** [comment]
Нашли причину проблемы. Не указано было соответствие пользователя хранилища пользователю с почтой Git (VSTS) в файле AUTHORS. Но хорошо бы выводить соответствующее сообщение в лог.

**Comment by nixel2007** [comment]
По идее гитсинк должен был коммитить от ИмяПользователяВХранилище@localhost. @Khorevaa?

**Comment by khorevaa** [comment]
@pavlicholeg вообще судя по логам там версия 2.4.. я ее не очень помню уже что и как
