### ISSUE TITLE
ошибка при распаковке обычных форм, v8unpack

### ISSUE THREAD

**Issue by ivvoronov** [oscript-library/gitsync#235]
ПРЕДУПРЕЖДЕНИЕ - Попытка удаления C:\Users\User\AppData\Local\Temp\tsxmue02.mr2.tmp закончилась неудачей, по причине {Модуль C:\Program Files (x86)\OneScript\lib\gitsync\oscript_modules\tempfiles\ВременныеФайлы.os / Ошибка в строке: 118 / Внешнее исключение (System.IO.IOException): The process cannot access the file 'Form.bin' because it is being used by another process.}
13:18:53 КРИТИЧНАЯОШИБКА - {Модуль C:\Users\IVoronov\AppData\Local\gitsync\plugins\gitsync-plugins\src\Классы\internal\v8unpack\Классы\РаспаковкаФорм.os / Ошибка в строке: 46 / Внешнее исключение (System.Reflection.TargetInvocationException): Exception has been thrown by the target of an invocation.}

Версия гитсинк - 3.1.0
Версия плагинов - 1.1.0
Версия oscript - 1.2.0.92

Отключить unpack не могу, он необходим.

**Comment by EvilBeaver** [comment]
По-моему, это уже кем-то когда-то решалось в гитсинке. Парни, кто помнит?

/cc @nixel2007 @khorevaa @artbear

**Comment by khorevaa** [comment]
Никак не решилось. Либа v8unpack не отпускает файл когда работает...... что приводит в данной ошибке..

**Comment by EvilBeaver** [comment]
А если принудительно ей делать ОсвободитьОбъект?

**Comment by khorevaa** [comment]
> А если принудительно ей делать ОсвободитьОбъект?

Не помогает!

**Comment by nixel2007** [comment]
@dmpas

**Comment by EvilBeaver** [comment]
> > А если принудительно ей делать ОсвободитьОбъект?
> 
> Не помогает!

Я могу доработать, @khorevaa скинь, пожалуйста место в гитсинке, где нужно сделать такое освобождение объекта, я сделаю PR в обе либы

**Comment by khorevaa** [comment]
Вообще где тл здесь надо.....

https://github.com/khorevaa/gitsync-plugins/blob/develop/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/unpackForm.os

**Comment by EvilBeaver** [comment]
Исправлено в PR https://github.com/oscript-library/gitsync/issues/235

@khorevaa просьба проверить и влить в основной репо

**Comment by ivvoronov** [comment]
Проблема не решена. Файл не освобождается.

**Comment by khorevaa** [comment]
@EvilBeaver  Выпущен релиз [gitsync-plugins 1.1.1](https://github.com/khorevaa/gitsync-plugins/releases/tag/1.1.1)

**Comment by ivvoronov** [comment]
Я правильно понимаю, что мне достаточно заменить файл gitsync-plugins-1.1.0.ospx в OneScript\lib\gitsync\embedded_plugins и заново инициализировать плагины?

**Comment by ivvoronov** [comment]
Проверил, проблема сохранилась.

**Comment by EvilBeaver** [comment]
@ivvoronov текст ошибки какой теперь точный?

**Comment by ivvoronov** [comment]
ПРЕДУПРЕЖДЕНИЕ - Попытка удаления C:\Users\IVoronov\AppData\Local\Temp\kd5wfpso.xpe.tmp закончилась неудачей, по причине {Модуль C:\Program Files\OneScript\lib\gitsync\oscript_modules\tempfiles\ВременныеФайлы.os / Ошибка в строке: 118 / Внешнее исключение (System.IO.IOException): The process cannot access the file 'Form.bin' because it is being used by another process.}
16:06:55 КРИТИЧНАЯОШИБКА - {Модуль C:\Users\IVoronov\AppData\Local\gitsync\plugins\gitsync-plugins\src\Классы\internal\v8unpack\Классы\РаспаковкаФорм.os / Ошибка в строке: 46 / Внешнее исключение (System.Reflection.TargetInvocationException): Exception has been thrown by the target of an invocation.}

**Comment by EvilBeaver** [comment]
Попробуй добавить код вокруг строки 46

```bsl
Попытка
  // строка 46
Исключение
   Сообщить(ИнформацияОбОшибке().ПодробноеОписаниеОшибки());
   ВызватьИсключение;
КонецПопытки;
```

и полученный текст сбросить сюда

**Comment by ivvoronov** [comment]
`ScriptEngine.Machine.ExternalSystemException: {Модуль C:\Users\IVoronov\AppData\Local\gitsync\plugins\gitsync-plugins\src\Классы\internal\v8unpack\Классы\РаспаковкаФорм.os / Ошибка в строке: 47 / Внешнее исключение (System.Reflection.TargetInvocationException): Exception has been thrown by the target of an invocation.}    
17:41:41 			Распаковщик = Новый ЧтениеФайла8(ФайлРаспаковки);
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Ionic.Zip, Version=1.9.3.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
17:41:41    at v8unpack.BlockReaderStream.AnalyzeState()
17:41:41    at v8unpack.BlockReaderStream..ctor(Stream basicStream)
17:41:41    at v8unpack.BlockReaderStream.ReadDataBlock(Stream reader)
17:41:41    at v8unpack.File8Reader.ReadFileList()
17:41:41    at v8unpack.File8Reader..ctor(Stream reader, Boolean dataPacked)
17:41:41    at v8unpack.File8Reader.Constructor(IValue filename)
17:41:41    --- End of inner exception stack trace ---
17:41:41    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
17:41:41    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
17:41:41    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
17:46:16    at ScriptEngine.Machine.TypeFactory.<>c__DisplayClass5_0.<FallbackConstructor>b__0(String typeName, IValue[] args)
17:46:16    at ScriptEngine.Machine.MachineInstance.NewInstance(Int32 argCount)
17:46:16    at ScriptEngine.Machine.MachineInstance.MainCommandLoop()
17:46:16    --- End of inner exception stack trace ---
17:46:16    at ScriptEngine.Machine.MachineInstance.MainCommandLoop()
17:46:16    at ScriptEngine.Machine.MachineInstance.ExecuteCode()
17:46:16 ОТЛАДКА - [oscript.lib.gitsync] - Откатываем файл VERSION после ошибки
17:46:16 ОТЛАДКА - [oscript.lib.gitsync] - ПутьКФайлуВерсий = <C:\J\workspace\MOSTRO\Gitsync_UPP\src\cf\VERSION>
17:46:16 ПРЕДУПРЕЖДЕНИЕ - Попытка удаления C:\Users\IVoronov\AppData\Local\Temp\23qwgwpj.2cf.tmp закончилась неудачей, по причине {Модуль C:\Program Files\OneScript\lib\gitsync\oscript_modules\tempfiles\ВременныеФайлы.os / Ошибка в строке: 118 / Внешнее исключение (System.IO.IOException): The process cannot access the file 'Form.bin' because it is being used by another process.}
17:46:16 КРИТИЧНАЯОШИБКА - {Модуль C:\Users\IVoronov\AppData\Local\gitsync\plugins\gitsync-plugins\src\Классы\internal\v8unpack\Классы\РаспаковкаФорм.os / Ошибка в строке: 47 / Внешнее исключение (System.Reflection.TargetInvocationException): Exception has been thrown by the target of an invocation.}`

**Comment by EvilBeaver** [comment]
@dmpas там оно Ionic не смогло найти. Можешь подсказать куда копнуть??

**Comment by dmpas** [comment]
Компонента собрана, видимо, ещё под `1.0.21` - там как раз этой версии Ионик Зип был.

**Comment by EvilBeaver** [comment]
@khorevaa можешь заменить макет компоненты?

**Comment by khorevaa** [comment]
@EvilBeaver Сейчас версия 1.0.4 dll компоненты. Вроде как последняя
@dmpas на какую версию заменить?

**Comment by ivvoronov** [comment]
Добрый день!
Получилось решить проблему?
